replicaCount: 1

image:
  repository: gcr.io/google-samples/microservices-demo/frontend
  tag: v0.10.0

containerPort: 8080

service:
  type: ClusterIP
  port: 80

env:
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: CART_SERVICE_ADDR
    value: "cartservice:7070"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - name: RECOMMENDATION_SERVICE_ADDR
    value: "recommendationservice:8080"
  - name: CHECKOUT_SERVICE_ADDR
    value: "checkoutservice:8080"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - name: AD_SERVICE_ADDR
    value: "adservice:8080"
  - name: SHOPPING_ASSISTANT_SERVICE_ADDR
    value: "shoppingassistservice:8080"

