replicaCount: 1

image:
  repository: gcr.io/google-samples/microservices-demo/currencyservice
  tag: v0.10.0

containerPort: 7000

service:
  type: ClusterIP
  port: 7000

env:
  - name: PORT
    value: "7000"
  - name: DISABLE_PROFILER
    value: "true"
  - name: DISABLE_TRACING
    value: "true"